$accent = {{ colors.primary.default.rgb }}
$text = {{ colors.on_surface.default.rgb }}
$time_color = {{ colors.secondary.default.rgb }}
$fail_color = {{ colors.error.default.rgb }}
$capslock_color = {{ colors.primary_container.default.rgb }}
$bg_path = {{ image }}
