foreground              #f0f0f0
background              #181818
selection_foreground    #181818
selection_background    #c0c0c0
cursor                  #f5f5f5
cursor_text_color       #181818
url_color               #c2c2c2
active_border_color     #c0c0c0
inactive_border_color   #3d3d3d
bell_border_color       #e0e0e0
active_tab_foreground   #181818
active_tab_background   #c0c0c0
inactive_tab_foreground #f0f0f0
inactive_tab_background #232323
tab_bar_background      #181818
mark1_foreground #181818
mark1_background #d4d4d4
mark2_foreground #181818
mark2_background #c0c0c0
mark3_foreground #181818
mark3_background #cccccc
color0 #303030
color8 #3d3d3d
color1  #acacac
color9  #acacac
color2  #cccccc
color10 #cccccc
color3  #e0e0e0
color11 #e0e0e0
color4  #c2c2c2
color12 #c2c2c2
color5  #d4d4d4
color13 #d4d4d4
color6  #b8b8b8
color14 #b8b8b8
color7  #f0f0f0
color15 #d0d0d0
